# Grunt aliases
---
# Build everything
build:
  - clean
  - 'build:css'
  - 'build:font'
  - 'build:images'
  - 'build:js'
  - 'build:i18n'
# Build depdencies
'build:dependencies':
  - 'build:dependencies:css'
  - 'build:dependencies:js'
  - 'build:dependencies:php'
'build:dependencies:css':
  - 'clean:css'
  - 'bowercopy:css'
  - 'replace:genericons'
  - 'newer:copy:vendorcss'
'build:dependencies:js':
  - 'bowercopy:js'
'build:dependencies:php':
  - 'composer:install'
  - 'clean:hybridcore'
  - 'newer:copy:hybridcore'
  - 'clean:flagshiplibrary'
  - 'newer:copy:flagshiplibrary'
  - 'clean:themehookalliance'
  - 'newer:copy:themehookalliance'
# Build CSS from Scss to production
'build:css':
  - 'clean:style'
  - 'build:dependencies'
  - 'rename:normalize'
  - 'newer:sass'
  - 'newer:autoprefixer'
  - 'newer:wpcss:css'
  - 'newer:replace:stylecomments'
  - 'newer:cssjanus'
  - 'newer:cssmin'
  - 'newer:replace:style'
  - 'newer:copy:css'
# Build Fonts from source to production
'build:font':
  - 'clean:font'
  - 'newer:copy:font'
# Optimise images from source to production
'build:images':
  - 'newer:imagemin'
  - 'newer:copy:images'
  - 'newer:copy:screenshot'
# Build JavaScript from assets to production
'build:js':
  - 'clean:js'
  - 'newer:concat:js'
  - 'newer:uglify'
  - 'newer:jsvalidate:theme'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain:flagshiplibrary'
  - 'makepot'
# Check health of the project
check:
  - 'scsslint'
  - 'jshint'
  - 'jsonlint'
  - 'jsvalidate'
  - 'jscs'
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Pre-commit hook task
commit:
  - 'check'
# Default task
default:
  - watch
newtheme:
  - 'replace:packagename'
  - 'build'
# Package the distribution files into a zip
package:
  - build
  - "compress:dist"
# Package developer files into a zip
'package:dev':
  - build
  - "compress:dev"
# Update reports
reports:
  - plato
